POST http://localhost:3000/auth/login
Content-Type: application/json


{
    "username" : "batman",
    "password" : "x"
}

###
GET http://localhost:3000/members
access-token: sampleAccessToken

###
GET http://localhost:3000/members/?memberid=1021
access-token: sampleAccessToken

###
POST http://localhost:3000/members
Content-Type: application/json
access-token: sampleAccessToken


{
    "firstname": "Sagar",
    "lastname": "Maharjan",
    "telephone": "985-000-6000",
    "address": "Huston, Texas, USA"
  }

###
GET http://localhost:3000/books
access-token: sampleAccessToken


###
 POST http://localhost:3000/books
 access-token: sampleAccessToken
 Content-Type: application/json


 {
    "isbn": "21-3-00",
    "title": "Fundamentals of C++ Programming",
    "max_checkout_length": 14,
    "authors": [
      "Keith Roth",
      "Preacher"
    ]
  }

###
POST http://localhost:3000/books/addbookcopy
Content-Type: application/json
access-token: sampleAccessToken


{
  "isbn" : "21-3-00",
  "noCopies" : 3
}

###
GET http://localhost:3000/books/?isbn=978-1-23
access-token: sampleAccessToken

###
GET http://localhost:3000/users
access-token: sampleAccessToken


###
GET http://localhost:3000/bookcopy
access-token: sampleAccessToken


###
GET http://localhost:3000/bookcopy/?isbn=111-3-00
access-token: sampleAccessToken

###
GET http://localhost:3000/bookcopy/111-3-00
access-token: sampleAccessToken

###
GET http://localhost:3000/bookcopy/avail/111-3-00
access-token: sampleAccessToken

###
PUT http://localhost:3000/bookcopy/avail/111-3-00
access-token: sampleAccessToken

###
POST http://localhost:3000/checkoutentries
Content-Type: application/json
access-token: sampleAccessToken


{
    "isbn": "111-3-00",
    "memberid": "1021",
    "issued_bookno": "7",
    "checkoutdate": "23/05/2024",
    "duedate": "30/05/2024"
  }