POST http://localhost:3000/auth/login
Content-Type: application/json


{
    "username" : "batman",
    "password" : "x"
}

###
GET http://localhost:3000/members

###
POST http://localhost:3000/members
Content-Type: application/json


{
    "firstname": "Sagar",
    "lastname": "Maharjan",
    "telephone": "985-000-6000",
    "address": "Huston, Texas, USA"
  }

###
GET http://localhost:3000/books


###
 POST http://localhost:3000/books
 Content-Type: application/json


 {
    "isbn": "111-3-00",
    "title": "Fundamentals of C++ Programming",
    "max_checkout_length": 14,
    "authors": [
      "Keith Roth",
      "Preacher"
    ]
  }

###
POST http://localhost:3000/books/addbookcopy
Content-Type: application/json


{
  "isbn" : "111-3-00",
  "noCopies" : 3
}

###
GET http://localhost:3000/books/?isbn=978-1-23

